### ISSUE TITLE
Feature request: Add `GroupBy`

### ISSUE THREAD

**Issue by cjwcommuny** [mtoohey31/iter#21]
Add `GroupBy` like [Rust](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.group_by) and [Python](https://docs.python.org/3/library/itertools.html#itertools.groupby).

**Comment by mtoohey31** [comment]
Hi @cjwcommuny, thanks for the feature request! I have an implementation for this in #22. Would you be interested in testing it out and/or doing code review on that before I merge it? No worries if not; I've written reasonably thorough tests and confirmed that it matches the semantics of the Rust and Python versions as I understand them but if you have time to take a look I'd appreciate it!
