### ISSUE TITLE
Wrong documentation of return value of `Reduce`

### ISSUE THREAD

**Issue by cjwcommuny** [mtoohey31/iter#23]
https://github.com/mtoohey31/iter/blob/5b87d291c9b04e497416459b03ce3744cae95699/iter.go#L386-L399

The doc says: "The boolean indicates whether the iterator was already empty, meaning that it could not be reduced."

But actually from the code we can see that it has the opposite meaning...

**Comment by mtoohey31** [comment]
Thanks for pointing that out, should be fixed in f0866e152aa33ff1ca181672d8ba26d00d3861fc! I also noticed a few other confusing uses of "whether" while looking at this, so those should be fixed now too.
